apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-letsencrypt-prod
  namespace: keycloak
spec:
  acme:
    email: kyungsu77777@gmail.com
    privateKeySecretRef:
      name: keycloak-letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
