apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: websocket
  namespace: argocd
spec:
  destination:
    namespace: websocket
    server: https://kubernetes.default.svc
  project: default
  source:
    path: websocket/local
    repoURL: https://github.com/gigigihuhuhu/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
