apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.15.3
      chart: cert-manager
      helm:
        valueFiles:
        - $values/cert-manager/prod/values.yaml
    - repoURL: 'https://github.com/gigigihuhuhu/gitops.git'
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

