apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next-exchange
  namespace: argocd
spec:
  destination:
    namespace: next-exchange
    server: https://kubernetes.default.svc
  project: default
  source:
    path: next-exchange/prod
    repoURL: https://github.com/gigigihuhuhu/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
